### ISSUE TITLE
Panic StreamedRecorder is not implement closeNotifier  .

### ISSUE THREAD

**Issue by stevensu1977** [nicolasazrak/caddy-cache#11]
src/github.com/mholt/caddy/caddyhttp/httpserver/responsewriterwrapper.go:41 - *cache.StreamedRecorder is not a closeNotifier

StreamedRecorder is not closeNotifier error .

**Comment by nicolasazrak** [comment]
Hi I seems that it should have been fixed with your pull request #12. Is there any way to reproduce it?

**Comment by stevensu1977** [comment]
I  used caddy:master (commit 3e2b1d145a0c60aee32821c353e8ecce4000ce3a), when you
add run.go caddy-cache, build is not error, but when you request any path (use directive cache  scope), get panic from responsewriterwrapper.go:41

![error](https://user-images.githubusercontent.com/6694421/27516661-d766eff8-59f0-11e7-9fcd-6ed02ed11786.png)

25/Jun/2017:21:51:41 +0800 [PANIC /api/log?m=months] src/github.com/mholt/caddy/caddyhttp/httpserver/responsewriterwrapper.go:41 - *cache.StreamedRecorder is not a closeNotifier

**Comment by stevensu1977** [comment]
already fix it
