### ISSUE TITLE
placeholder status

### ISSUE THREAD

**Issue by dusty** [nicolasazrak/caddy-cache#16]
Is there a placeholder that can be used to log out the cache status same as status_header?

Thanks!

**Comment by nicolasazrak** [comment]
Currently no, but looking thought the log middleware code I have discovered that it exposes a Replacer struct (https://github.com/mholt/caddy/blob/master/caddyhttp/log/log.go#L35). It seems to be to allow custom directives to add more placeholders, which is exactly what is needed for this. I will investigate a little more to see if that can be added.

**Comment by nicolasazrak** [comment]
@dusty It's done in https://github.com/nicolasazrak/caddy-cache/commit/f1af22d69362ab66f4d192d5c78cbe6a1c5a6e45 and published in caddy page
