### ISSUE TITLE
Improper use of net/http.Header.Set

### ISSUE THREAD

**Issue by tgulacsi** [nicolasazrak/caddy-cache#2]
https://github.com/nicolasazrak/caddy-cache/blob/master/cache.go#L25 uses Header.Set to add individual header values, but uses https://godoc.org/pkg/net/http/#Header.Set, which replaces all values with this one - this is wrong.

I'd use 
```
	m := w.Header()
	for k, values := range response.HeaderMap {
 		m[k] = append(m[k][:0], v...)
	}
```

**Comment by nicolasazrak** [comment]
Thanks it's fixed now in 25084ff92d69570ad2bf1034c7a6d8489fbdd14e I've used headers.Add() which internally do exactly the same.
