### ISSUE TITLE
Avoid caching and serving empty 304 responses 

### ISSUE THREAD

**Issue by rickles42** [nicolasazrak/caddy-cache#28]
(Please take this with a large grain of salt, as I'm very new to this area. This could be a total non-issue due to my own errors.)

**Summary**: It seems like caddy-cache is caching and serving successful (but empty) 304 responses to conditional requests using the `If-None-Match` header. This results in the cache sometimes serving an empty page to some visitors.

**Details**: I _think_ the sequence of events I see happening is:

1. User Alice sends request `GET index.html`
2. Caddy sends response `200 (OK) [contents of index.html]`. and caddy-cache stores the contents of index.html.
3. Some time after max-age has passed for index.html, Alice sends request `GET index.html` but includes the `If-None-Match` and `ETag` headers, so that the server can avoid re-sending the contents of index.html if it hasn't changed.
4. Caddy handles these headers correctly and sends response `304 (Not Modified) [empty response]`
5. *Caddy-cache stores the *empty data* from the 304 response, keyed to the request for index.html.*
6. User Bob sends request `GET index.html`
7. Caddy-cache serves Bob the (empty) cached response.
8. Bob sees an empty index.html.

Again, I could have something wrong here, so please don't hesitate to question my theory.

In case it's important, here's the relevant portion of my Caddyfile:

```
    cache {
        match_path /api
    }

    header / Cache-Control "max-age=3600"
    header /api Cache-Control "max-age=30"
```

My small website has an expensive API, so I'd like to cache its results for 30s. But I don't particularly need to cache the rest of my site. I've added the `cache` directive in an attempt to selectively cache the `/api` path, but since this appears to cache the rest of the site anyway (see #26) I put the extra `header` directive in so at least I can control how long the rest gets cached. I don't know if this issue occurs with other configurations but I'm guessing it's likely.

I see that my use of `header` means that _all_ responses from Caddy will include a max-age, even the 304 responses, but I would have thought the cache would be smart enough to recognize a 304 response and avoid caching it.

**Comment by smlx** [comment]
I'm also seeing this behaviour, and can replicate the exact behaviour described by @rickles42

**Comment by nicolasazrak** [comment]
I swear I tested this. I'll try to see if I can reproduce it but I don't have much time to see it in a few days. But if you would like to investigate, the code that decides which request should be cached is in https://github.com/nicolasazrak/caddy-cache/blob/master/rules.go#L52 and on https://github.com/pquerna/cachecontrol.

**Comment by naiba** [comment]
Hello @smlx @nicolasazrak , I have encountered this problem, but I have solved by #36 . The reason for the problem is that the origin has cache control, and the cache plugin needs to add a `cache-control: no-cache` request header when requesting the origin.

```
cache {
    header_upstream CacheControl no-cache
}
```

**Comment by kleveralt** [comment]
> Hello @smlx @nicolasazrak @rickles42 , I have encountered this problem, but I have solved by #36 . The reason for the problem is that the origin has cache control, and the cache plugin needs to add a `cache-control: no-cache` request header when requesting the origin.
> 
> ```
> cache {
>     header_upstream Cache-Control no-cache
> }
> ```

I tried you code branch and your method but it did not work, upstream was recieving "Cache-Control: no-cache" but did not honor it. nginx will always respondes 304 when browser is sending an Etag or a If-Modified-Since header.

The right ways to solve this issue is ugly, like this,

```
proxy {
        header_upstream -If-Modified-Since
        header_upstream -Etag
}
```

**Comment by nicolasazrak** [comment]
@kleveralt this should be easier to solve than modifying the proxy middleware. The cache should not store 304 responses. It can do that modifying https://github.com/nicolasazrak/caddy-cache/blob/master/rules.go#L46 (I'm not sure what cacheobject library decides to do with 304 statuses). That should be really easy. Would you like to submit a PR for this?

The hardest part is actually answering 304 if the etag of the request matches the cached response. It should be done in https://github.com/nicolasazrak/caddy-cache/blob/master/handler.go#L80. Not doing that can actually hurt perfomance.

**Comment by kleveralt** [comment]
@nicolasazrak I cann't code Golang. But I think you may store the backend reponse headers together with the data body in cache objects, so you can compare them with the request header, like nginx proxy_cache dose.

**Comment by NicolasLM** [comment]
I don't want to sound to grumpy but this is a pretty serious issue. It makes caddy-cache broken by default for any upstream that understands etags.

It leads to hard to debug scenarios: it took me quite a while to understand why some of my users had randomly empty CSS and JS files.

**Comment by nicolasazrak** [comment]
It should be fixed in the new version. I'm publishing now. Please, try it and reopen if the issue still happens
