### ISSUE TITLE
Cache using Header Filter

### ISSUE THREAD

**Issue by martindale** [nicolasazrak/caddy-cache#3]
I'd like to be able to selectively cache assets based on a header, such as `Content-Type`.  This would be useful for caching things like images, while still serving HTML directly.

i.e., 

```
cache {
  match {
    header Content-Type image/*
  }
}
```

**Comment by nicolasazrak** [comment]
Seems like a good feature, I'm not having much free time but I will see if I can do something in the next few days

**Comment by nicolasazrak** [comment]
@martindale I've pushed a new commit in master that adds this feature. The only thing that is not in there is the syntactic sugar of `Content-Type image/*`, you have to specify which content types you want, because that works with content type but does not apply to other headers.

**Comment by martindale** [comment]
Shipped to production.  Thanks!
