### ISSUE TITLE
How to control cached files http header?

### ISSUE THREAD

**Issue by naiba** [nicolasazrak/caddy-cache#33]
It seem not to be controlled.

```
https://www.example.cc/usr/themes/Single/css/kico.css

response headers:
accept-ranges: bytes
content-length: 27270
content-type: text/css; charset=utf-8
date: Wed, 31 Oct 2018 07:14:08 GMT
etag: "pg9yotl1i"
last-modified: Mon, 08 Oct 2018 10:05:17 GMT
server: Caddy                   //this header maybe upstream's or local caddy's
server: NaibaCDN                //this header is setting by myself
status: 200
x-cache-status: hit
```

And this is my Caddyfile

```
www.example.cc {
    tls me@example.com
    header / Server NaibaCDN
    cache
    proxy / https://www.example.cc {
        transparent
        header_downstream -Server
    }
}
```

I'm already set `header_downstream` and `http.header` why has **two Server** header?

**Comment by nicolasazrak** [comment]
I believe this is a Caddy problem. Is your origin another caddy server? The cache never adds the server header, but if your origin already sends it, then the cache server where `caddy-cache` is running is going to add it again. If you make the test for example to have a proxy to another caddy server (without the cache), you'll notice that the same happens

**Comment by naiba** [comment]
hi @nicolasazrak ,thank you for replay. 

I think that like the design of `http.proxy`, the middleware needs to control the header itself, instead of being controlled by **caddy**.

Looked at the source code of **http.cache**, it will copy the remote HTTP header, but **caddy** will not process these HTTP headers again, so there will be problems in the issue.

**Comment by nicolasazrak** [comment]
Sorry for not answering, I was really busy. I don't se anything wrong with the code but I still don't understand the problem it solves. Why would you want the cache to modify the headers and why isn't it possible with the headers plugin for example? Is there anything that I'm missing? In your case you probably need to stop sending the `server` header in the origin, I'm not sure why `header_downstream` is not working, but even with that, it shouldn't be something that must be done from the cache.

About the hangs/stucks requests you mention in #35. It seems you are right and the `subscription.go` might be the reason, would you like to create a separete pull request with a test that reproduces the issue?

**Comment by naiba** [comment]
header control I think it's caddy's design, it will not modify plugin return headers. so this plugin need a header control.and #35, It's hard to repreduce.when you just get first package(maybe 56k i test),then cancel request, and request again, it will hangs/stucks.maybe you can add me as a member.2018年11月27日 18:48，Nicolas <notifications@github.com>写道：Sorry for not answering, I was really busy. I don't se anything wrong with the code but I still don't understand the problem it solves. Why would you want the cache to modify the headers and why isn't it possible with the headers plugin for example? Is there anything that I'm missing? In your case you probably need to stop sending the server header in the origin, I'm not sure why header_downstream is not working, but even with that, it shouldn't be something that must be done from the cache.
About the hangs/stucks requests you mention in #35. It seems you are right and the subscription.go might be the reason, would you like to create a separete pull request with a test that reproduces the issue?
