### ISSUE TITLE
Static website cache

### ISSUE THREAD

**Issue by ahoeg** [nicolasazrak/caddy-cache#46]
Would it possible to serve only static cache content to the client and refresh the cache content from the backend webserver by an given interval? 
Exclude from caching by path to reach dynamic cms backends.

I try to serve a static copy of a dynamic website because of security problems with some cms out there... Serve the page as static copy should be absolute secure and the backend path would be saved by caddy basicauth.

**Comment by nicolasazrak** [comment]
Mmm probably caddy-cache isn't the best solution for your problem. Maybe you could have a separate script that runs with cron that fetches your dynamic page and you only use caddy for the static content. Cache is intended to be a Middleware, for every request, i don't think it makes sense for your use case
