### ISSUE TITLE
How to build this with caddy?

### ISSUE THREAD

**Issue by schollz** [nicolasazrak/caddy-cache#7]
Could you explain more about how to build this with Caddy? I've looked [at the docs](https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-Directives) and I'm still not sure how to begin.

**Comment by nicolasazrak** [comment]
Do this to fetch the code
```sh
go get -u github.com/mholt/caddy
go get -u github.com/nicolasazrak/caddy-cache
cd $GOPATH/src/github.com/mholt/caddy
go get ./...
cd $GOPATH/src/github.com/nicolasazrak/caddy-cache
go get ./...
```

Then update the file `$GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go` and just import 
```go
_ "github.com/nicolasazrak/caddy-cache"
``` 

And finally build caddy with: 
```sh
cd $GOPATH/src/github.com/mholt/caddy/caddy
./build.bash
```
 
And that's it.

**Comment by schollz** [comment]
Awesome! I didn't realize it was so easy!
Thanks
