### ISSUE TITLE
Error when getting caddy-cache plugin

### ISSUE THREAD

**Issue by dgeorgievski** [nicolasazrak/caddy-cache#8]
Hi,

I am getting this error when trying to get the caddy-cache plugin

> go get github.com/nicolasazrak/caddy-cache
> 
> ../../../../nicolasazrak/caddy-cache/setup.go:171: c.IncrNest undefined (type *caddy.Controller has no field or method IncrNest)

Which versions of Caddy servers are supported at this time?

Dimitar

**Comment by nicolasazrak** [comment]
It seems caddy has changed its API, I have checked and it works with `v0.9.4`. I'll try to fix it and make it compile with `v0.9.5`.

**Comment by nicolasazrak** [comment]
It's solved now. I used to rely on `IncrNesting()` method as a hack to support nesting in `match` directive. Had to change the config usage.

**Comment by dgeorgievski** [comment]
Thanks @nicolasazrak . It works now.
